version: '3'

networks:
  default:
    driver: bridge
  web:
    external: true

services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    container_name: ${PROJECT}-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "${APP_PORT}:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT}.rule=Host(`${DOCKER_DOMAIN}`)"
      - "traefik.http.services.${PROJECT}.loadbalancer.server.port=80"
    networks:
      - default
      - web
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: always
    container_name: ${PROJECT}-db
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    networks:
      - default

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT}-pma
    ports:
      - "${PMA_PORT}:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma_${PROJECT}.rule=Host(`${PMA_DOMAIN}`)"
    networks:
      - default
      - web
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db